site_name: "semantix"
site_description: "Build your own searchable data for AI deep research"
site_url: "https://.github.io/semantix"
repo_url: "https://github.com//semantix"
repo_name: "/semantix"
site_dir: "site"

nav:
  - Home:
    - Overview: index.md
    - Changelog: changelog.md
  - Development:
    - Contributing: contributing.md
    - Code of Conduct: code_of_conduct.md

theme:
  name: material
  palette:
    primary: deep purple
    accent: teal
  font:
    text: Open Sans
    code: Fira Code


markdown_extensions:
  - admonition
  - pymdownx.emoji
  - pymdownx.magiclink
  - pymdownx.snippets:
      check_paths: true
      base_path: ".."
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
  - toc:
      permalink: "#"

plugins:
  - search
